baseURL = "/"
languageCode = "en-us"
title = "Eelke van den Bos"
theme = "coder"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "eelkevdbos"

[params]
    author = "Eelke van den Bos"
    info = "Coder. Innovator. Educator."
    description = "Blog, contact details and more."
    keywords = "blog,developer,personal"
    avatarurl = "https://www.gravatar.com/avatar/7a7ebce7a6375553982a6bc1c6f7474a.jpg?s=200"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = "KvK: 75404869 | BTW: NL002192436B83"

    hidecredits = true
    hidecopyright = true
#
#    rtl = false
#
#    math = true
#    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/eelkevdbos/"
[[params.social]]
    name = "Gitlab"
    icon = "fab fa-gitlab fa-2x"
    weight = 2
    url = "https://gitlab.com/eelkevdbos/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/eelkevdbos/"

# Menu links
#[[menu.main]]
#    name = "Blog"
#    weight = 1
#    url  = "/posts/"
#[[menu.main]]
#    name = "About"
#    weight = 2
#    url = "/about/"
